

## 谷歌笔试题：break与try

请问以下代码的输出是什么？

```python
try:
    for i in range(3):
        try:
            1 / 0
        except ZeroDivisionError:
            raise ZeroDivisionError("Error: You divided by zero!")
        finally:
            print("Finally executed")
            break
except ZeroDivisionError:
    print("Outer ZeroDivisionError exception caught")
	
```

- A 

Outer ZeroDivisionError exception caught

- B
Error: You divided by zero!

- C

Error: You divided by zero!
Finally executed

- D

Finally executed
- E

None of the above